### ISSUE TITLE
Can't place blocks

### ISSUE THREAD

**Issue by GreyLake** [Shiirroo/ManHunt#2]
Able to break, craft, etc. but cannot place blocks, reoccurring issue with all players (Including administrators). No other plugins installed. Almost acts as if there's spawn protection but only for placing blocks. Minecraft version tested 1.16.5.

Edit. Previous versions such as version 1.2 works with placing blocks. Still unable to place blocks in version 1.4.3.

**Comment by GreyLake** [comment]
UPDATE:

Turns out the plugin can't even run on normal Spigot and Bukkit servers, only functional of Paper servers and Paper equivilents. 

Tested on:

Bukkit 1.16.5: Failed
Bukkit 1.17.1: Failed
Spigot 1.16.5: Failed
Spigot 1.17.1: Failed
Paper 1.16.5: Works (Can't place Blocks)
Paper 1.17.1: Works (Can't place Blocks)
Purpur 1.17.1: Works (Can't place Blocks)

I guess the 1.4.3 version isn't functional, I'll have to stick with the old 1.2 version for a while..

**Comment by Shiirroo** [comment]
First of all, thank you very much for your report. **I apologize for the long wait**.
I noticed the problem with the newer version **as well (Bukkit || Spigot)** Paper should work with the newest version.
I should get around to releasing a fix for it this week. Should the new version result in further bugs, please let me know.

**Comment by Shiirroo** [comment]
e85341c  I was able to upload the first update for the fixes with it. I will have to continue testing.
