### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by MrLiam2614** [Shiirroo/ManHunt#4]
I suggest adding a custom scoreboard;
One for "waiting" and one for "in game".

We should be able to use some placeholders by the plugin like remaining time, speedrunners alive, hunters, assassins and thigs like that

**Comment by Shiirroo** [comment]
Sorry I don't feel scoreboard that way. But I'll keep it in mind in case I need to work on it. 
You can display the game time at any time with a click in the settings or simply /ManHunt Timer
