### ISSUE TITLE
kits for group

### ISSUE THREAD

**Issue by pouyarisk** [Shiirroo/ManHunt#6]
I want to host a manhunt game with guns with your plugin but my problem is that I can't give the players any item exactly after the game start and also I can not give them before the run because they use it earlier and that is cheating

I wonder if you can make a feature that allows us to make kits for each group so when the game start, they start with those items inside their inventory.
that's gonna help me so much

thanks for reading

**Comment by Shiirroo** [comment]
Hello, there should be no problem giving the items to the player with a runTaskLater, after the game has started for the players. 
Did you create your own plugin for the kits?

**Comment by pouyarisk** [comment]
No, I didn't.
