### ISSUE TITLE
Some GUIs not working

### ISSUE THREAD

**Issue by srnyx** [Shiirroo/ManHunt#7]
**Describe the bug**
Some errors with `AnvilGUI` are causing a lot of the GUI config stuff to not work.

**To Reproduce**
1. Open `Settings` GUI
2. Open `ManHunt Configuration:`
3. Try to change one of the clock/integer values
4. It won't open any GUI and you'll see errors in the console

**Versions:**
- Server software: Paper 1.18.2
- Plugin version: 1.6.9

**Comment by Shiirroo** [comment]
Problem should have been resolved with the c5c9d69 fix. 1.18.2 was not supported at all. Update to spigotmc coming soon
