### ISSUE TITLE
Add simple /manhunt command.

### ISSUE THREAD

**Issue by MrShadow-X** [Shiirroo/ManHunt#9]
Add message after typing /manhunt (without subcommand), like this in luckperms plugin.

![image](https://user-images.githubusercontent.com/77029131/169650153-fac313ba-1884-480f-aba4-cb993d93d051.png)

**Comment by Shiirroo** [comment]
I'll take a look

**Comment by Shiirroo** [comment]
You always have the option to run a few sub commands. Do you want the help to be executed?

**Comment by MrShadow-X** [comment]
> You always have the option to run a few sub commands. Do you want the help to be executed?

No, just simple message. (Do you have discord?, because i have some bugs that i want to talk about.)

**Comment by Shiirroo** [comment]
You are welcome to join the community server. https://discord.gg/sfktcwgTVS

**Comment by Shiirroo** [comment]
Added in 48f9f8f
